apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::706310580439:role/eksctl-eksctl-demo-nodegroup-ng-a6-NodeInstanceRole-r2Fhg9kkvqfK
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::706310580439:role/UdacityFlaskDeployCBKubectlRole
      username: build

kind: ConfigMap
metadata:
  creationTimestamp: "2024-12-30T16:18:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1404"
  uid: 00b84522-fc26-461d-a308-ae1282d9309f
